vich_uploader:
    db_driver: orm

    mappings:
        livre_image:
            uri_prefix: /uploads/livres
            upload_destination: "%kernel.project_dir%/public/uploads/livres"
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
